/*
 * This file is generated by jOOQ.
 */
package com.mysqljooq.assetmanageunit.jooq.domain;


import com.mysqljooq.assetmanageunit.jooq.domain.tables.Comments;
import com.mysqljooq.assetmanageunit.jooq.domain.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooqtest
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqtest.COMMENTS</code>.
     */
    public static final Comments COMMENTS = com.mysqljooq.assetmanageunit.jooq.domain.tables.Comments.COMMENTS;

    /**
     * The table <code>jooqtest.POSTS</code>.
     */
    public static final Posts POSTS = com.mysqljooq.assetmanageunit.jooq.domain.tables.Posts.POSTS;
}
